name: clean_business_logic
description: This is clean architecture library for business logic layer

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider:
  equatable:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
